### ISSUE TITLE
Dbman expects a db with the superuser username to exists

### ISSUE THREAD

**Issue by lucas-dclrcq** [hef/dbman#88]
Hi,

First, great work with this operator ! I was looking for something like this :)

I've encountered a small issue : 
```
  Type     Reason              Age    From   Message
  ----     ------              ----   ----   -------
  Normal   CreatingDatabase    19s    dbman  Creating database `firefly_iii`
  Warning  ReconcilingError    5m19s  dbman  Tokio Postgres Error: db error: FATAL: database "homelab_admin" does not exist
  Warning  ReconcilingError    10m    dbman  Tokio Postgres Error: db error: FATAL: database "homelab_admin" does not exist
  Warning  ReconcilingError    10m    dbman  Tokio Postgres Error: db error: FATAL: database "homelab_admin" does not exist
```

My superuser is named homelab_admin, and it seems that dbman expects a database with the same name to exist before reconciling any other database.

If i manually create the database, it can resume reconciling databases and users.

Is this an expected behavior ?

Best regards,

Lucas

**Comment by hef** [comment]
Can you post your Database CR?

**Comment by hef** [comment]
This should be address in https://github.com/hef/dbman/commit/e5baefb35d08487962001ef17528e1c7c460b763

Turns out this _is_ expected postgres behavior.  postgres assumes that you specified a database with the role name if you didn't specify a seperate `dbname=`.   It looks like pgadmin sneaks `dbname=template1` into the conn_string if you don't specify one.  I made some adjustments so that the error message will tell you what to do.
